add WebMapTileServiceRaster support (WMTS)
CesiumGS/cesium-unity pull request #430
Opened 2024-03-06 15:36 UTC by tal952

Added WMTS support.
Based it on the WMS current support.

2024-03-06 15:40 UTC, tal952 commented
Hello @j9liu , Given that this Pull Request builds upon your prior contributions to the WMS support, could you kindly take a moment to review it? Your insights would be greatly appreciated.

2024-03-07 06:19 UTC, tal952 commented
He @kring , signed the Contributor License Agreement 👍

2024-03-13 11:40 UTC, kring commented
Really appreciate the PR @tal952, and we'll review this as soon as we can. It might be a little bit though, we have a long review backlog at the moment.

2024-03-20 22:31 UTC, j9liu requested changes
Thanks @tal925 for the PR! This is a solid start, I reviewed and left some feedback where needed. Mainly, I'm concerned about the difference in overlay parameters between this PR and Cesium for Unreal. Other comments are just minor style changes / nitpicks.

Do you have a test URL that you're willing to share, so that I can verify it works?

2024-03-20 22:31 UTC, j9liu commented on Editor/CesiumWebMapTileServiceRasterOverlayEditor.cs
> +                "Image width.");
```suggestion
                "The width of the image tiles in pixels.");
```

2024-03-20 22:31 UTC, j9liu commented on Editor/CesiumWebMapTileServiceRasterOverlayEditor.cs
> +                "Image height.");
```suggestion
                "The height of the image tiles in pixels.");
```

2024-03-20 22:31 UTC, j9liu commented on Editor/CesiumWebMapTileServiceRasterOverlayEditor.cs
> +                "The style name for WMTS requests, default value is \"default\".");
```suggestion
                "The MIME type for images to retrieve from the server.");
            EditorGUILayout.DelayedTextField(this._format, formatContent);
            
            GUIContent styleContent = new GUIContent(
                "Style",
                "The style name for WMTS requests.");
```

2024-03-20 22:31 UTC, j9liu commented on Editor/CesiumWebMapTileServiceRasterOverlayEditor.cs
> +﻿using UnityEditor;
Could you reorder the properties so they match the order in Cesium for Unreal?

![image](https://github.com/CesiumGS/cesium-unity/assets/32226860/36f558bf-a856-4324-912b-ffed3a930d97)

We like to have consistency between engines when possible, so people won't get confused between different UIs.

2024-03-20 22:31 UTC, j9liu commented on Runtime/CesiumWebMapTileServiceRasterOverlay.cs
> +        /// The minimum level-of-detail supported by the imagery provider, default value is 0.
```suggestion
        /// The minimum level-of-detail supported by the imagery provider.
```

2024-03-20 22:31 UTC, j9liu commented on Runtime/CesiumWebMapTileServiceRasterOverlay.cs
> +        /// The maximum level-of-detail supported by the imagery provider, default value is 25.
```suggestion
        /// The maximum level-of-detail supported by the imagery provider.
```

2024-03-24 09:35 UTC, tal952 commented on Runtime/CesiumWebMapTileServiceRasterOverlay.cs
> +        public bool useGeographicProjection
That is very strange, the default in CesiumJS and Cesium-native is the WebMercatorProjection, I'm not sure why they made useWebMercatorProjection and not useGeographicProjection.
It looks like we need to decide between CesiumJS and Cesium-native default and Cesium-Unreal.
I think we should go with the CesiumJS and Cesium-native, what do you think?

2024-03-24 09:44 UTC, tal952 commented on Runtime/CesiumWebMapTileServiceRasterOverlay.cs
> +        public string tileMatrixSetID
It's very uncommon to use this fields, I think that if anyone needs them, they just implement them. (It's just kind of lot of work to add this uncommon fields)

2024-03-24 09:45 UTC, tal952 commented on native~/Runtime/src/CesiumWebMapTileServiceRasterOverlayImpl.cpp
> +  }
https://github.com/CesiumGS/cesium-unity/pull/430#discussion_r1536776088

2024-03-24 09:47 UTC, tal952 commented on Runtime/CesiumWebMapTileServiceRasterOverlay.cs
> +        /// https://services.ga.gov.au/gis/services/NM_Culture_and_Infrastructure/MapServer/WMTSServer
Changed to https://tile.openstreetmap.org/{TileMatrix}/{TileCol}/{TileRow}.png

2024-03-24 09:53 UTC, tal952 commented on Runtime/CesiumWebMapTileServiceRasterOverlay.cs
> +        }
AFAIK it's very standard to have "default" style, but I'm not sure about that. I'll leave it empty.

2024-03-25 17:25 UTC, j9liu commented on Runtime/CesiumWebMapTileServiceRasterOverlay.cs
> +        public bool useGeographicProjection
Oh that's strange... Let's keep the settings consistent with CesiumJS and Cesium Native. Thank you for pointing that out to me!

2024-03-25 17:27 UTC, j9liu commented on Runtime/CesiumWebMapTileServiceRasterOverlay.cs
> +        public string tileMatrixSetID
Sounds good @tal952. Thanks for letting me know 👍

2024-03-25 17:29 UTC, j9liu commented
@tal952 thanks for the responses to my comments above. Let me know when I should take another look!

2024-03-25 17:45 UTC, tal952 commented
Hey @j9liu , looks like I fixed everything you mentioned, if you can take another look it would be awesome 🙏🙏

2024-03-25 18:43 UTC, j9liu commented
Looks good to me @tal952, thanks for the contribution! I'll do a follow-up PR to add those extra settings to the overlay, just for parity with Unreal.

2024-03-25 18:43 UTC, merged